Material UI changes
LucRademakers/zuydspeelt-frontend pull request #18
Opened 2023-06-16 10:09 UTC by KAJ045

2023-06-16 21:08 UTC, codeine requested changes
Ziet er goed uit! Alleen een klein aantal aanpassingen voor de best practices aan te houden. De aanpassingen zie je hieronder.

2023-06-16 21:08 UTC, codeine commented on app/login/page.tsx
> +    window.location.href = "/";
Remove onClick handler.

2023-06-16 21:08 UTC, codeine commented on app/register/page.tsx
> +    window.location.href = "/login";
Remove onClick handler.

2023-06-16 21:08 UTC, codeine commented on app/register/page.tsx
> +              onClick={goToLogin}
Vervang `<Button>` met een Link element. (Niet `<a>` maar `<Link>`)

2023-06-16 21:08 UTC, codeine commented on app/login/page.tsx
> +              onClick={goToHome}
Vervang `<Button>` met een Link element. (Niet `<a>` maar `<Link>`)

2023-06-16 21:12 UTC, DrTuup commented
> Ziet er goed uit! Alleen een klein aantal aanpassingen voor de best practices aan te houden. De aanpassingen zie je hieronder. 

Ma boi is smert

2023-06-19 08:12 UTC, KAJ045 commented
> Ziet er goed uit! Alleen een klein aantal aanpassingen voor de best practices aan te houden. De aanpassingen zie je hieronder.

Ik snap wat je bedoeld, in dit geval zou Link een goeie optie zijn. Maar keep in mind dat je in de toekomst de buttons meer functies wilt laten uitvoeren dan alleen navigatie. Denk aan credentials of dergelijke andere functies. Dat kan alleen met onClick functie en niet met Link.

2023-06-19 09:29 UTC, codeine commented
Je hebt gelijk. Wellicht is het dan een goed idee om een onSubmit handler te maken `<form onSubmit={handleSubmit}` en de knop een `<input type="submit"` te maken.

2023-06-23 06:53 UTC, DrTuup approved these changes
Prima jong 🚀

2023-06-23 06:59 UTC, DrTuup commented
Heb de merge conficts nog even opgelost.

2023-06-23 07:01 UTC, codeine approved these changes

2023-06-23 07:04 UTC, merged