Searchbar component
LucRademakers/zuydspeelt-frontend pull request #22
Opened 2023-06-17 11:34 UTC by Bruce2103932

Met deze zoekbar kunnen games opgezocht worden. Dit is nog niet met de database verbonden. De lijst van games bevindt zich in de code van de searchbar zelf (searchbar.tsx). Deze code staat in de folder 'components'. Voor de games zijn een aantal mock pagina's aangemaakt. Deze bevinden zich in de folder 'games'. De afbeeldingen bevinden zich in de 'public' folder. Zie de README.md hoe de searchbar in pagina's toegevoegd kan worden. Daarnaast zijn er een aantal Jest tests aangemaakt binnen de __tests__ folder.

2023-06-17 13:53 UTC, codeine requested changes
Zoals je kan zien is de check gefaald. Je kunt even controleren wat de oorzaken zijn en de fixes committen.

2023-06-17 20:32 UTC, Bruce2103932 commented
Excuses daarvoor. Bedankt voor je feedback. Ik ben de errors aan het proberen op te lossen en zal zo snel mogelijk weer wat laten weten.

2023-06-17 23:42 UTC, Bruce2103932 commented
Het heeft een aantal uren geduurd, maar ik heb alle conflicten en errors opgelost. Als het goed is moet mijn branch nu klaar zijn om te mergen met dev.

2023-06-18 10:48 UTC, codeine approved these changes

2023-06-18 10:49 UTC, merged